plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-2.4.2.cjs

packageExtensions:
  # requires @rollup/plugin-node-resolve, which has an unmet rollup peerDependency
  "@web/dev-server@0.1.*":
    dependencies:
      "rollup": "^1.20.0||^2.0.0"
